name: Arduino Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile Arduino Sketch
      uses: arduino/compile-sketches@v1
      with:
        sketch-paths: |
          examples/QuadpodExample.ino
